apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fermentation-station-agent-add-backstage-kubernetes-id
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lukasb27/fermentation-station-agent.git
    targetRevision: add-backstage-kubernetes-id
    path: k8s
    kustomize:
      images:
        - lukasball/fermentation-station-agent=lukasball/fermentation-station-agent:add-backstage-kubernetes-id
      commonAnnotations:
        prNumber: "31"
        sha: 7f6d88ee21bc69f7e3d4a3d2919d2a3b56eb43a7
  destination:
    server: https://kubernetes.default.svc
    namespace: add-backstage-kubernetes-id
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true