apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fermentation-station-agent-fix-ephemeral-env-orphaned-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lukasb27/fermentation-station-agent.git
    targetRevision: fix-ephemeral-env-orphaned-resources
    path: k8s
    kustomize:
      images:
        - lukasball/fermentation-station-agent=lukasball/fermentation-station-agent:fix-ephemeral-env-orphaned-resources
      commonAnnotations:
        prNumber: "32"
        sha: a15322a039d15cf026a3baa431266b5e7f00b993
  destination:
    server: https://kubernetes.default.svc
    namespace: fix-ephemeral-env-orphaned-resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true