apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golden-path-p1-test-1-main
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lukasb27/golden-path-p1-test-1.git
    targetRevision: main
    path: k8s
    kustomize:
      images:
        - ghcr.io/lukasb27/golden-path-p1-test-1=ghcr.io/lukasb27/golden-path-p1-test-1:main
        - ghcr.io/lukasb27/golden-path-p1-test-1-integ-tests=ghcr.io/lukasb27/golden-path-p1-test-1-integ-tests:latest
      commonAnnotations:
        prNumber: ""
        commitSha: main
        repoSlug: lukasb27/golden-path-p1-test-1
  destination:
    server: https://kubernetes.default.svc
    namespace: golden-path-p1-test-1-main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
